project_id = "mktsqcxbcaexyxmenafp"

[functions.chat]
verify_jwt = false

[functions.neohi-ai]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = false

[functions.realtime-voice]
verify_jwt = false

[functions.extract-memory]
verify_jwt = false

[functions.neoforge-ai]
verify_jwt = false

[functions.cache-cleanup]
verify_jwt = false

[functions.cache-warming]
verify_jwt = false
